import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import "cal-sans";
import { ThemeProvider } from '@/components/theme-provider';
import AppTopbar from '@/components/app-topbar';
import { Toaster } from '@/components/ui/sonner';
import ReactQueryProvider from '@/components/react-query-provider';
import Blobs from '@/components/blobs';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Solvro - Cocktails',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <ReactQueryProvider>
                        <AppTopbar />
                        <main className='z-10 relative'>
                            {children}
                            <Toaster richColors />
                        </main>
                        <Blobs />
                    </ReactQueryProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
